### ISSUE TITLE
Waterfox Download has undefined variables

### ISSUE THREAD

**Issue by tobiasjwm** [autopkg/jpiel-recipes#2]
The filename for the download is coming out as "%NAME%-%BRANCH%-%WFversion%.dmg". This is causing the recipe stack to fail in my environment.

Autopkg is throwing the error: "Use of undefined key in variable substitution: u'BRANCH'"

It appears that the filename string is using "%BRANCH%" but should be using "%APPBRANCH%". 

I also suspect that the regex pattern in line 25 should be using < and > instead of "&lt;" and "&gt;". I saw this change in another recipe in the last week.

**Comment by jpiel** [comment]
I fixed the variable name, sorry about that. I changed the variable name for readability after testing the recipe, and i forgot to retest after... :)

About the < and >, i had to use \&lt; and \&gt; because putting directly < and > didn't work.
