### ISSUE TITLE
URLTextSearcher: Error: No match found on URL - Localized-LibreOffice

### ISSUE THREAD

**Issue by mallej** [autopkg/jpiel-recipes#7]
apparently something has changed in the URL and the regex needs to be adjusted. Unfortunately, I have had no success so far.

[Localized-LibreOffice.download.recipe]
(https://github.com/autopkg/jpiel-recipes/blob/master/Localized-LibreOffice/Localized-LibreOffice.download.recipe)
```

'RELEASE': 'fresh',
 'pkginfo': {'blocking_applications': ['LibreOffice'],
             'catalogs': ['testing'],
             'category': 'Productivity',
             'description': 'LibreOffice with fr Language pack',
             'developer': 'The Document Foundation',
             'display_name': 'LibreOffice fr',
             'name': 'LibreOffice_fr',
             'unattended_install': True,
             'unattended_uninstall': True},
 'verbose': 4}
URLTextSearcher
{'Input': {'re_flags': ['IGNORECASE'],
           're_pattern': 'LibreOffice (?P<smallversion>[0-9]+(\\.[0-9]+)+) '
                         '\\([^)]*\\) -\n'
                         '\t\t\t\t\t\tfresh Branch',
           'url': 'https://www.libreoffice.org/download/release-notes/'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Curl command: ['/usr/bin/curl', '--compressed', '--location', 'https://www.libreoffice.org/download/release-notes/']
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 122, in main
    groupmatch, groupdict = self.re_search(content)
  File "/Library/AutoPkg/autopkglib/URLTextSearcher.py", line 109, in re_search
    raise ProcessorError(f"{NO_MATCH_MESSAGE}: {self.env['url']}")
autopkglib.ProcessorError: No match found on URL: https://www.libreoffice.org/download/release-notes/
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
No match found on URL: https://www.libreoffice.org/download/release-notes/
Failed.
Receipt written to /Users/munkipkg/Library/AutoPkg/Cache/local.munki.Localized-LibreOffice/receipts/Localized-LibreOffice-receipt-20230522-160824.plist

The following recipes failed:
    Localized-LibreOffice.munki
        Error in local.munki.Localized-LibreOffice: Processor: URLTextSearcher: Error: No match found on URL: https://www.libreoffice.org/download/release-notes/
```

**Comment by jpiel** [comment]
Hmmm

I don’t understand. I don’t have this issue at all, and the pattern 
i have is not the same than the one in your logs.



  'RELEASE': 'fresh',
  'pkginfo': {'blocking_applications': ['LibreOffice'],
              'catalogs': ['testing'],
              'category': 'Productivity',
              'description': 'LibreOffice with fr Language pack',
              'developer': 'The Document Foundation',
              'display_name': 'LibreOffice fr',
              'name': 'LibreOffice_fr',
              'unattended_install': True,
              'unattended_uninstall': True},
  'verbose': 3}
URLTextSearcher
{'Input': {'re_flags': ['IGNORECASE'],
            're_pattern': 'LibreOffice 
(?P<smallversion>[\\d\\.]+)\\.\\d+ [^ ]+ '
                          '- fresh Branch',
            'url': 
'https://www.libreoffice.org/download/release-notes/'}}
URLTextSearcher: No value supplied for result_output_var_name, setting 
default value of: match
URLTextSearcher: Found matching text (smallversion): 7.5
URLTextSearcher: Found matching text (match): 7.5
{'Output': {'match': '7.5', 'smallversion': '7.5'}}
URLTextSearcher


-- 
Jayce Piel --  ***@***.*** --  06-16-76-24-31
Directeur du Département Informatique Fédération Française de Tir

**Comment by mallej** [comment]
hello again. sorry for being quit.

so what i found out is, that if i use 
```
<key>RELEASE</key>
<string>fresh</string>
```
it works but it downloads the wrong version. 
It downloads 7.6.4 which is the stable(still) version at the moment.
Fresh version would be 24.2.0.
I don't know why there is this gap in version numbers.

and
when i use 			
```
<key>RELEASE</key>
<string>still</string>
```
we got the error
`Processing Localized-LibreOffice.munki...
URLTextSearcher
{'Input': {'re_flags': ['IGNORECASE'],
           're_pattern': 'LibreOffice (?P<smallversion>[\\d\\.]+)\\.\\d+ [^ ]+ '
                         '- still Branch',
           'url': 'https://www.libreoffice.org/download/release-notes/'}}
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Found matching text (smallversion): 7.5
URLTextSearcher: Found matching text (match): 7.5
{'Output': {'match': '7.5', 'smallversion': '7.5'}}
URLTextSearcher
{'Input': {'re_flags': ['IGNORECASE'],
           're_pattern': 'LibreOffice (?P<version>7.5\\.\\d+) release notes',
           'result_output_var_name': 'match',
           'url': 'https://www.libreoffice.org/download/download/'}}
No match found on URL: https://www.libreoffice.org/download/download/
Failed.`

**Comment by jpiel** [comment]
Hi, 

According to LibreOffice WebSite, 7.6.4 is the fresh version, and the still version is the 7.5.9.

[https://www.libreoffice.org/download/release-notes/]
<img width="973" alt="image" src="https://github.com/autopkg/jpiel-recipes/assets/12051594/2115d417-3005-4220-8f0e-41d4a8371f12">

Looks like LibreOffice forgot to update their realease-notes page.
And that's why the still keyword doesn't work anymore since it doesn't find this old version in the download page.

Version 24.2.0 is pretty new (24 comes from the year i guess) and i'll wait a bit before changing the process of my recipes, maybe they will finally update their release-notes page...

**Comment by jpiel** [comment]
I've sent a bugreport to libreoffice team for the webpage issue.

**Comment by jpiel** [comment]
They fixed the website page and changed the naming.
I updated the recipe and you must now use Latest/Previous instead of fresh/still
