### ISSUE TITLE
Code Signature error with Anydesk recipe

### ISSUE THREAD

**Issue by jelockwood** [autopkg/jpiel-recipes#9]
@jpiel 
As of last night and today I am now getting the following error from your Anydesk recipe.

```WARNING: com.github.jpiel.munki.Anydesk is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...```
 
```Code signature verification failed. Note that all verifications can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.```
```Failed.```

I did try updating the trust info in my override, I did try running your download recipe directly. Adding the following to my override has for now got round the problem.

```	        <key>DISABLE_CODE_SIGNATURE_VERIFICATION</key>```
```        	<string>true</string>```

I suspect the issue is that the developer has changed their signature information but your CodeSignatureVerifier section in your download recipe has now obsolete information and no longer works.

**Comment by jpiel** [comment]
Sorry for the delay, i was very busy. The signature check should be fixed now.
